#+TITLE: Coasian Motion: Deforestation and the Central Tendency to Disperse
#+AUTHOR: Dan Hammer, Robin Kraft, David Wheeler
#+OPTIONS:     toc:nil num:nil 
#+LATEX_HEADER: \usepackage{comment}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{amstex}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{dcolumn}
#+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage{caption} 
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX: \setlength{\parindent}{0in}
#+LATEX: \renewcommand{\X}{{\bf X}}
#+LATEX: \renewcommand{\D}{{\bf D}}
#+LATEX: \renewcommand{\I}{\mathbb{I}}
#+LATEX: \renewcommand{\st}{\hspace{8pt} \mbox{s.t.} \hspace{6pt}}
#+LATEX: \renewcommand{\with}{\hspace{8pt} \mbox{with} \hspace{6pt}}
#+LATEX: \renewcommand{\y}{{\bf y}}
#+STARTUP: fninline

* Introduction

Tropical deforestation may contribute over 15% of annual greenhouse
gas emissions. Any viable effort to mitigate climate change will have
to address deforestation.  International efforts to curb the rate of
deforestation have thus far been composed of a series bilateral
agreements, despite calls for a comprehensive, global mechanism.  The
United Nations has proposed the Reducing Emissions from Deforestation
and Degradation (REDD) framework to directly address local incentives
to convert forest to fiscally productive lands.  This grand Coasian
bargain, however, has been frustrated by many factors, including high
transaction costs, discord among member countries, and poorly defined
property rights.  The number of frustrating factors is an increasing
function of the number of relevant member countries.  The devil is in
the details, and the amount of details rises exponentially with the
number of contracting agents.  As with any network graph, the number
of edges increases exponentially with the number of nodes.  The UN
REDD framework is effectively an attempt to consolidate negotiations;
but this effort has met limited success due in part to a constantly
shifting natural and political landscape for forest conservation.\\

This paper demonstrates that the basis for a comprehensive agreement
is becoming more complex.  Specifically, this paper utilizes satellite
imagery to show that the dispersion of forest clearing across
administrative units is increasing.  The number of countries with a
substantial share of forest clearing activities is increasing,
potentially forestalling a truly comprehensive conservation framework.  

* Forest clearing detection

The data on forest clearing activity is based on the classification of
stacked images from the Moderate Resolution Image Spectroradiometer
(MODIS) sensor.  Both time series and cross-sectional characteristics
are extracted from the images, and then compared against historical
(2000-2005) forest cover loss data (Hansen, 2008).  The classification
rule is derived from the comparison, and then applied to recent
imagery.  The final output is a probability of forest cover loss
between January 1, 2000 and the acquisition date of the most recent
MODIS image.  The resulting alerts are highly accurate when compared
against other, production-level forest clearing alerts.  A notable
result is that this relatively simple algorithm produces accurate
alerts, especially in capturing the broad trends of forest clearing
activity.\\

The algorithm to collect forest clearing alerts consists of four
principal stages:\\

1. Time series characteristics from the derived Normalized Difference
   Vegetation Index (NDVI) are extracted for each 500-meter pixel in
   the humid tropics (MOD13A1).  These characteristics include
   long-term trends and variation in the NDVI, along with short-term
   break detection (citation needed).  The techniques are common in
   time series econometrics, often in the context of financial
   indices.  The established econometric techniques are repurposed to
   account for natural cycles.

2. Cross-sectional methods are employed on derived images to identify
   clusters of the extracted time dependent characteristics.  This
   includes, for example, the largest detected drop in the NDVI series
   for a cluster of pixels.  The largest, neighborhood drop is
   ascribed as a pixel-level characteristic, acting as a smoothing
   operator across the image, much like a moving average over time.

3. Pixel-level attributes from the time series and cross-sectional
   analysis are compared against historical data on forest cover loss.
   The precise method of comparison is a logistic, ridge classifier
   (citation needed), implemented in parallel to accommodate very
   large and distributed data sets.  A separate classification rule is
   generated and applied for each ecoregion (citation needed)
   independently.

4. The classification rule is applied to the most recent MODIS imagery
   for each ecoregion to produce a probability of forest cover loss.
   The probability can be interpreted as a measure of \emph{strength
   of signal} of clearing activity.  There is substantial noise via
   measurement error or cloud cover, which may mask the spectral
   signals associated with forest conversion.  The continuous index
   rises as the signal of forest cover loss persists over time.  

The precise algorithm, along with documentation and detailed analysis,
is stored as an open source code repository, with a growing number of
contributors.  The final output can be replicated from the raw
imagery; every minor step, of which there are many, is open for public
review.  The result is a highly accurate alerting system of forest
cover loss in the humid tropics.  



* 

The probability $p_{it}$ indicates the likelihood of forest clearing
activity within grid cell $i$ for the interval between December 2005
and period $t$.  The probability measure is the output from a logistic
classifier, where the features are extracted from layered satellite
imagery and compared against the Hansen (2008) data set.  Additional
description of the algorithm are presented in /Materials and Methods/.
The spatial resolution for this study is 500-meters and the temporal
frequency is 16-days.  There are 191? periods during the study
interval between 2008 and April 2013.  

The algorithm to identify forest clearing activity for each 500m grid
cell in the humid tropical biome is described in the /Materials and
Methods/ section.  Let $p_{it}$ indicate the probability of clearing
activity for pixel $i$ and the time interval between December 2005 and
period $t$.  The probability is the output from a logistic classifier,
indicating the intensity of satellite signals that have historically
been associated with deforestation.  The deforestation rate for
administrative unit $j$ is the number of pixels that were tagged with
deforestation for the first time in period $t$.

The incremental deforestation rate $d_{jt}$ expresses the number of
500m grid cells tagged with clearing activity in administrative unit
$j$ during time interval $t$.  The algorithm to identify pixel-level
clearing activity from satellite imagery is described in /Materials
and Methods/.  The output from the algorithm is 

The data used for this paper are the forest clearing alerts from
Forest Monitoring for Action (FORMA), a pan-tropical forest monitoring
system developed by Hammer et al. (2013).  The data are derived from
remotely sensed data, primarily from the MODIS sensor.  FORMA reports
the probability of forest clearing activity at 16-day intervals for
each 500-meter, forest pixel in the humid tropics.  Pixel time series
are created by stacking satellite imagery, merging the spectral
histories with ancilliary data, including rainfall.  Non-forest pixels
are removed from analysis by screening out pixels with VCF < 25 as
done in Hansen (2008).  The algorithm extracts characteristics from
the pixel time series that correspond to unnatural patterns in data.
The characteristics are, in turn, matched against the forest cover
loss hotspots data set.  The result is a continually updated
characterization of clearing activity for each period, or a
probability of forest clearing activity by the specified time
interval.\\

The accuracy assessment in Hammer et al (2013) indicates that a
confidence threshold of 0.5 produces a robust alerting system that
minimizes false positives and successfully identifies the
industrial-scale clearing activity that is the focus of this paper.
The continuous probability range is valuable because it provides
information on the relative intensity of clearing across pixels as
opposed to a binary indicator.  The aggregate measure of clearing
activity in an administrative unit in this paper is calculated for
each interval as the summed probabilities, conditional on the
probabilities exceeding a confidence threshold of 0.5.  Analysis of
the dynamics of forest clearing acitivity are made possible by the
high frequency of the updates.  Higher resolultion systems are
suitable to focused areal assessments, but cannot adequately
characterize the sub-annual dynamics at a time-scale commensurate with
economic drivers of deforestation.  The dynamics and geographic scope
of FORMA data make this paper possible.

* Definition of dispersion

Dispersion is the degree of spread of a phenomenon over space and/or
time. In this paper, we consider dispersion of deforestation as
characterizing the degree of concentration of clearing activity in a
geographic area. The measure of dispersion of clearing activity at any
particular time is based on an aggregated measure of clearing, given
by FORMA. The geographic aggregations of interest in this paper -
countries, provinces and sub-provinces - are arbitrary, but important
given that these units define the various levels of decision making
that affect deforestation.

Let i be the pixel index, and cj be the set of pixel indices in
administrative unit j. The aggregate level of clearing activity in
administrative unit j and time period t is given by equation X.

\begin{equation}
\label{eq:aggregation}
D_{jt} = \sum_{i \in C_j} \I (p_{it} \geq 0.5) \cdot p_{it}
\end{equation}

We characterize the spread of clearing activity across all
administrative units in the sample by using Shannon's entropy
criterion, defined in equation Y.

\begin{equation}
\label{eq:entropy}
E_{t} = -\sum_{j = 1}^{n} \frac{D_{jt}}{D_t} \log_{2} \frac{D_{jt}}{D_t} \with D_{t} = \sum_j D_{jt}
\end{equation}

E ranges from 0 to 1, and larger values of E indicate higher
dispersion across units.  A value of 1 is a uniform distribution, with
equal values for all units. A higher value of E across countries, for
example, would indicate that clearing is less clustered at the the
country level. More concretely, this would indicate that clearing is
spreading beyond Brazil and Indonesia.

* Geographic dispersion

At various levels of disaggregation, the patterns of forest clearing
dispersion remain similar.  We consider the country, provincial, and
sub-province administrative units because that's where forest
management policy is created or implemented.  

** Country 

Upward trend.  And seasonal.  Is entropy low when deforestation rates
are high, or vice versa?  Plot the sd of clearing activity over the
mean of clearing activity :: coefficient of variation.  Find out
whether CV trend is going up or down.

TODO: why seasonal? individual country's seasonality?  


** Province and sub-province level

TODO: do the same for prince and sub-province level.

** Tree entropy

Look at the dispersion trends /within a country/.  This corresponds
with the scenario of countries being at international negotiations,
who in turn deal with local provinces for actual conservation.  How
tenable are the promises made at the international negotiating table?

Consider Indonesia the world and look at the dispersion across
sub-provinces.  The question is whether the promises made by the big
players are credible.  Indonesia's position becomes more difficult,
since they have to interact with more local leaders.

\begin{figure}[h]
        \centering
        \begin{subfigure}[b]{0.3\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/iso-entropy.png}
                \caption{{\bf Country}}
                \label{fig:para}
        \end{subfigure}
        \begin{subfigure}[b]{0.3\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/prov-entropy.png}
                \caption{{\bf Province}}
                \label{fig:borneo}
        \end{subfigure}
        \begin{subfigure}[b]{0.3\textwidth}
                \centering
                \includegraphics[width=\textwidth]{images/gadm-entropy.png}
                \caption{{\bf Subprovince}}
                \label{fig:borneo}
        \end{subfigure} 
        \caption{Entropy over time for three levels of administrative units}
\label{fig:rates}
\end{figure}

* Implications for conservation

Our results indicate that tropical forest clearing is dispersing
rapidly across countries, particularly in the regions near Brazil and
Indonesia. This development may have significant implications for
conservation strategy through its impact on the economics of
negotiating, monitoring and enforcing international agreements. Since
we focus on forest clearing as a carbon pollution problem, we provide
a Coasian interpretation of the issue (Coase, 1960).[fn::We recognize
that tropical forest clearing also entails grave risks for many
endangered species, as well as large potential costs from the loss of
local ecosystem services. Resolution of these problems may well
require additional measures that are not discussed in this paper.] In
the Coasian view, parties damaged by polluting emissions have three
basic options for redress: (1) receiving compensation for damage
and/or reducing pollution through legal action against polluters; (2)
reducing pollution via government regulation of polluters; (3) paying
polluters to reduce their emissions.\\

As Coase and many others have noted, the appropriate choice depends on
the relative benefits and costs of each option in a particular
context, as well as the status of relevant legal and governmental
institutions. In the case of forest policy, international donors have
focused on Coasian option (3) --- payment for pollution reduction ---
because global legal and regulatory constraints make options (1) and
(2) infeasible. The traditional payment system has focused on direct
support for protected areas in tropical forests. However, clearing has
continued in many protected areas, and donors have responded by
initiating programs that compensate countries for successful
protection. These programs, coordinated by the United Nations, are
collectively known as REDD+: Reducing Emissions from Deforestation and
Forest Degradation in Developing Countries.\\

Unfortunately, our evidence suggests that the Coasian bargains
envisioned by REDD+ are becoming less attractive as forest clearing
disperses more widely. The essential problem resides in transactions
costs. If pollution is concentrated in a few countries, compensation
negotiations are not excessively costly because few parties are
involved. As pollution disperses across countries, however,
negotiation costs escalate even if total pollution remains
constant. This is particularly true if weak governance in new entrants
raises the cost of monitoring and enforcing compensation agreements.\\

From a traditional Coasian perspective, then, we are forced to
conclude that the rapid dispersal of forest clearing has significantly
raised the cost of tropical forest conservation. Fortunately, we
believe that the Coasian prospectus can be expanded to a fourth option
(“Coase+”) that may provide an attractive alternative to REDD+ in some
cases.\\

Coase+ shifts the locus of the pollution problem from production to
consumption. It reflects the fact that pollution is a byproduct of
commodity production for final delivery to consumers.  In cases where
products can be linked explicitly to polluting producers, the Coasian
option set expands because damaged parties can seek redress through
legal or governmental actions directed at polluters’ products, or
through selective promotion of products from “clean” producers. Coase+
measures can be enacted locally, because they do not depend on the
assent of other countries. Such measures may be preferable to REDD+
programs in cases where consumption is highly concentrated (making
single-country measures effective) and polluting production is widely
dispersed (making compensation negotiations costly).\\

Is Coase+ an attractive alternative in the real world? The answer
depends on assessment of at least five factors. The first is the
concentration of consumption relative to polluting production in the
tropical forest sector. Our evidence for rapid dispersion of forest
clearing is striking, but consumption has also been de-concentrating
internationally, as the global consumption share of low- and
middle-income countries has increased. However, this process has been
much slower than the accelerated dispersion of forest clearing during
the past few years. On balance, the change in relative concentration
has shifted the balance toward Coase+ measures.\\

The second factor is information. Can products be reliably linked to
their polluting sources?  "Pollution accounting" is feasible for bulk
commodities whose value chains are relatively short, because product
attribution is clear, only shipment in bulk lots is cost-effective,
and transshipment in bulk through third countries to avoid detection
is both expensive and futile.  Many commodities produced on
previously-forested tropical land fall into this category (e.g., palm
oil, beef, soybeans).\\

The third factor relates to domestic politics in high-income areas
where consumption is concentrated (e.g., North America, Western
Europe). On balance, the political case for Coase+ measures seems
favorable. For taxpayers, there is no immediately-clear distinction
between Coase+ and REDD+ measures based on compensation or promotion
of “clean” products, because both options involve public
expenditure. Ceteris paribus, taxpayers should prefer the more
cost-effective approach. Where product taxation is employed as a
Coase+ measure, offsetting reductions in other taxes can be
implemented. For products such as beef, soybeans and vegetable oil,
where domestic (non-tropical-forest) producers compete with tropical
forest producers, the domestic producers should support Coase+
taxation because it will improve their competitive status.\\

The fourth factor relates to international trade relations. Existing
WTO rules can accommodate tariffs or regulatory controls for imported
products that have negative production or consumption externalities,
as long as these measures are not directed at specific countries. 2 In
principle, this includes regulation or taxation of imported
commodities produced in cleared tropical forest areas or,
equivalently, subsidies for products that are not produced in those
areas.\\

The fifth factor is the disposition of revenues from Coase+ taxation
of imported products. In principle, the taxing country could rebate
all revenues to the country whose products are taxed.  This would
preserve the basic rationale for Coase+ product taxation --- raising
the relative price of commodities produced on cleared tropical forest
land --- while ensuring overall revenue neutrality for the exporting
country.\\

In summary, we believe that the rapid dispersal of clearing in
tropical forests warrants a re- assessment of policies for reducing
CO2 emissions from those areas. Two of the three traditional Coasian
options are infeasible, because the international legal/regulatory
regime will not supportthem. By default, protected-area programs and
REDD+ policies have adopted Coasian option (3) – direct payments to
polluters for reducing their pollution. However, as Coase and others
have long noted, the transactions cost of option (3) escalates as the
number of polluters increases.  To address this problem, we propose an
additional Coasian option set (Coase+) that focuses on transactions
via consumption rather than transactions via production. Coase+
measures seem feasible for major tropical forest products, and they
may well offer an attractive alternative to REDD+ in some cases.\\

Conservation negotiations rely on a series of joint arrangements.
Each arrangement takes a significant amount of time to specify.  Even
if the number of relevant players in the negotiation rises linearly,
the number of joint arrangements will rise exponentially.  The
complexity and barriers to a common conservation agreement increase
exponentially as tropical deforestation becomes more dispersed.  The
basis for this observation is founded in both operations research and
contract theory [find citations].\\

The increased dispersion also suggest the possibility of geographic
leakage, given that deforestation has already begun to spread.  Static
coefficient of friction is much greater than the dyanmic coefficient
of friction; and this analogy applies to economic processes with
increasing returns to scale.

* Appendix: Materials and Methods



